# Generated by Django 3.0.7 on 2020-06-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='was_included_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
